export const USER_REQUEST = 'USER_REQUEST';
export const USER_RESPONSE_SUCC = 'USER_REQUEST_SUCC';
export const USER_RESPONSE_ERROR = 'USER_RESPONSE_ERROR';
export const CHECK_TYPECARD = 'CHECK_TYPECARD';
